# Generated by Django 3.1.2 on 2020-11-17 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_data',
            old_name='mail',
            new_name='likes',
        ),
        migrations.AddField(
            model_name='image_data',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
