# Generated by Django 3.1.2 on 2020-11-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0002_auto_20201118_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_data',
            name='submitted_by',
            field=models.CharField(default='ME', max_length=70),
            preserve_default=False,
        ),
    ]
