# Generated by Django 3.1.2 on 2020-11-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0003_image_data_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_data',
            name='image_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image_data',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image_data',
            name='submitted_by',
            field=models.CharField(default='ME', max_length=70),
        ),
    ]
