# Generated by Django 3.1.2 on 2020-11-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0006_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.FileField(upload_to='project1/static/project1/images'),
        ),
    ]
